// <auto-generated />
using System;
using Calculatrice_TP2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculatrice_TP2.Migrations
{
    [DbContext(typeof(CalculatriceContext))]
    [Migration("20260417144101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Calculatrice_TP2.Models.Calcul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Equation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Resultat")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Calculs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Equation = "2 + 2",
                            Resultat = 4.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
